services:
  client:
    build: ./client
    container_name: client-app
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./client:/app  
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    network_mode: host  

  server:
    build: ./server-app
    container_name: server-app
    volumes:
      - ./server-app:/app
    ports:
      - "6000:6000"
    network_mode: host 
